services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 40s

  transactions-api:
    build:
      context: .
      dockerfile: TransactionsApi/Dockerfile
    container_name: transactions-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      elasticsearch:
        condition: service_healthy

  sidecar-api:
    build:
      context: .
      dockerfile: SidecarApi/Dockerfile
    container_name: sidecar-api
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  esdata: