//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.InternalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mysamplewcfservice.com/2012/08", ConfigurationName="InternalService.InternalService")]
    public interface InternalService {
        
        // CODEGEN: Generating message contract since the wrapper name (InternalOperation-A) of message InternalOperation-ARequest does not match the default value (InternalOperationA)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperation-A", ReplyAction="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperation-AResp" +
            "onse")]
        ClientApp.InternalService.InternalOperationAResponse InternalOperationA(ClientApp.InternalService.InternalOperationARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperationB", ReplyAction="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperationBRespo" +
            "nse")]
        string InternalOperationB();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InternalOperation-A", WrapperNamespace="http://www.mysamplewcfservice.com/2012/08", IsWrapped=true)]
    public partial class InternalOperationARequest {
        
        public InternalOperationARequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InternalOperation-AResponse", WrapperNamespace="http://www.mysamplewcfservice.com/2012/08", IsWrapped=true)]
    public partial class InternalOperationAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InternalOperation-AResult", Namespace="http://www.mysamplewcfservice.com/2012/08", Order=0)]
        public string InternalOperationAResult;
        
        public InternalOperationAResponse() {
        }
        
        public InternalOperationAResponse(string InternalOperationAResult) {
            this.InternalOperationAResult = InternalOperationAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InternalServiceChannel : ClientApp.InternalService.InternalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalServiceClient : System.ServiceModel.ClientBase<ClientApp.InternalService.InternalService>, ClientApp.InternalService.InternalService {
        
        public InternalServiceClient() {
        }
        
        public InternalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.InternalService.InternalOperationAResponse ClientApp.InternalService.InternalService.InternalOperationA(ClientApp.InternalService.InternalOperationARequest request) {
            return base.Channel.InternalOperationA(request);
        }
        
        public string InternalOperationA() {
            ClientApp.InternalService.InternalOperationARequest inValue = new ClientApp.InternalService.InternalOperationARequest();
            ClientApp.InternalService.InternalOperationAResponse retVal = ((ClientApp.InternalService.InternalService)(this)).InternalOperationA(inValue);
            return retVal.InternalOperationAResult;
        }
        
        public string InternalOperationB() {
            return base.Channel.InternalOperationB();
        }
    }
}
