//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.AddService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mysamplewcfservice.com/2012/08", ConfigurationName="AddService.InternalService")]
    public interface InternalService {
        
        // CODEGEN: Generating message contract since the wrapper name (InternalOperation-A) of message InternalOperation-ARequest does not match the default value (InternalOperationA)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperation-A", ReplyAction="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperation-AResp" +
            "onse")]
        ClientApp.AddService.InternalOperationAResponse InternalOperationA(ClientApp.AddService.InternalOperationARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperationB", ReplyAction="http://www.mysamplewcfservice.com/2012/08/InternalService/InternalOperationBRespo" +
            "nse")]
        string InternalOperationB();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InternalOperation-A", WrapperNamespace="http://www.mysamplewcfservice.com/2012/08", IsWrapped=true)]
    public partial class InternalOperationARequest {
        
        public InternalOperationARequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InternalOperation-AResponse", WrapperNamespace="http://www.mysamplewcfservice.com/2012/08", IsWrapped=true)]
    public partial class InternalOperationAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InternalOperation-AResult", Namespace="http://www.mysamplewcfservice.com/2012/08", Order=0)]
        public string InternalOperationAResult;
        
        public InternalOperationAResponse() {
        }
        
        public InternalOperationAResponse(string InternalOperationAResult) {
            this.InternalOperationAResult = InternalOperationAResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InternalServiceChannel : ClientApp.AddService.InternalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalServiceClient : System.ServiceModel.ClientBase<ClientApp.AddService.InternalService>, ClientApp.AddService.InternalService {
        
        public InternalServiceClient() {
        }
        
        public InternalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.AddService.InternalOperationAResponse ClientApp.AddService.InternalService.InternalOperationA(ClientApp.AddService.InternalOperationARequest request) {
            return base.Channel.InternalOperationA(request);
        }
        
        public string InternalOperationA() {
            ClientApp.AddService.InternalOperationARequest inValue = new ClientApp.AddService.InternalOperationARequest();
            ClientApp.AddService.InternalOperationAResponse retVal = ((ClientApp.AddService.InternalService)(this)).InternalOperationA(inValue);
            return retVal.InternalOperationAResult;
        }
        
        public string InternalOperationB() {
            return base.Channel.InternalOperationB();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Add", ReplyAction="http://tempuri.org/IService/AddResponse")]
        int Add(int i, int j);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ClientApp.AddService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ClientApp.AddService.IService>, ClientApp.AddService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int i, int j) {
            return base.Channel.Add(i, j);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddService.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AdminOperationA", ReplyAction="http://tempuri.org/IAdminService/AdminOperationAResponse")]
        string AdminOperationA();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/AdminOperationB", ReplyAction="http://tempuri.org/IAdminService/AdminOperationBResponse")]
        string AdminOperationB();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : ClientApp.AddService.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<ClientApp.AddService.IAdminService>, ClientApp.AddService.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AdminOperationA() {
            return base.Channel.AdminOperationA();
        }
        
        public string AdminOperationB() {
            return base.Channel.AdminOperationB();
        }
    }
}
