//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.CustomBinds {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomBinds.ICustomBind")]
    public interface ICustomBind {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomBind/HelloWorld", ReplyAction="http://tempuri.org/ICustomBind/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomBind/GetCounter", ReplyAction="http://tempuri.org/ICustomBind/GetCounterResponse")]
        int GetCounter();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomBindChannel : ClientApp.CustomBinds.ICustomBind, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomBindClient : System.ServiceModel.ClientBase<ClientApp.CustomBinds.ICustomBind>, ClientApp.CustomBinds.ICustomBind {
        
        public CustomBindClient() {
        }
        
        public CustomBindClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomBindClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomBindClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomBindClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public int GetCounter() {
            return base.Channel.GetCounter();
        }
    }
}
