@TokenGenerator_HostAddress = http://localhost:5062

GET {{TokenGenerator_HostAddress}}/weatherforecast/
Accept: application/json
###

### Generate Token
POST {{TokenGenerator_HostAddress}}/api/AuthToken/generate
Content-Type: application/json
{
  "email": "teacher@gmail.com",
  "password": "teach123"
}

### Response
