//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by slsvcutil, version 4.0.50826.0
// 
namespace MaFamilleService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CompositeType", Namespace = "http://schemas.datacontract.org/2004/07/MaFamilleService")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private bool BoolValueField;

        private string StringValueField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                if ((this.BoolValueField.Equals(value) != true))
                {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StringValueField, value) != true))
                {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AlbumModel", Namespace = "http://schemas.datacontract.org/2004/07/WcfService1.Model")]
    public partial class AlbumModel : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string AlbumNameField;

        private byte[] ImageStreamField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlbumName
        {
            get
            {
                return this.AlbumNameField;
            }
            set
            {
                if ((object.ReferenceEquals(this.AlbumNameField, value) != true))
                {
                    this.AlbumNameField = value;
                    this.RaisePropertyChanged("AlbumName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageStream
        {
            get
            {
                return this.ImageStreamField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImageStreamField, value) != true))
                {
                    this.ImageStreamField = value;
                    this.RaisePropertyChanged("ImageStream");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TsunamiModel", Namespace = "http://schemas.datacontract.org/2004/07/WcfService1.Model")]
    public partial class TsunamiModel : object, System.ComponentModel.INotifyPropertyChanged
    {

        private decimal CanvasLeftField;

        private decimal CanvasTopField;

        private byte[] ImageStreamField;

        private decimal RotationField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CanvasLeft
        {
            get
            {
                return this.CanvasLeftField;
            }
            set
            {
                if ((this.CanvasLeftField.Equals(value) != true))
                {
                    this.CanvasLeftField = value;
                    this.RaisePropertyChanged("CanvasLeft");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CanvasTop
        {
            get
            {
                return this.CanvasTopField;
            }
            set
            {
                if ((this.CanvasTopField.Equals(value) != true))
                {
                    this.CanvasTopField = value;
                    this.RaisePropertyChanged("CanvasTop");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageStream
        {
            get
            {
                return this.ImageStreamField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImageStreamField, value) != true))
                {
                    this.ImageStreamField = value;
                    this.RaisePropertyChanged("ImageStream");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rotation
        {
            get
            {
                return this.RotationField;
            }
            set
            {
                if ((this.RotationField.Equals(value) != true))
                {
                    this.RotationField = value;
                    this.RaisePropertyChanged("Rotation");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CustomException", Namespace = "http://schemas.datacontract.org/2004/07/WcfService1.Model")]
    public partial class CustomException : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string MessageField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "MaFamilleService.IService")]
    public interface IService
    {

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IService/GetData", ReplyAction = "http://tempuri.org/IService/GetDataResponse")]
        System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);

        string EndGetData(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction = "http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(MaFamilleService.CompositeType composite, System.AsyncCallback callback, object asyncState);

        MaFamilleService.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IService/GetPhotos", ReplyAction = "http://tempuri.org/IService/GetPhotosResponse")]
        System.IAsyncResult BeginGetPhotos(System.AsyncCallback callback, object asyncState);

        System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> EndGetPhotos(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IService/GetTsunamiPhotos", ReplyAction = "http://tempuri.org/IService/GetTsunamiPhotosResponse")]
        System.IAsyncResult BeginGetTsunamiPhotos(System.AsyncCallback callback, object asyncState);

        System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel> EndGetTsunamiPhotos(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IService/GetPhoto", ReplyAction = "http://tempuri.org/IService/GetPhotoResponse")]
        System.IAsyncResult BeginGetPhoto(System.AsyncCallback callback, object asyncState);

        byte[] EndGetPhoto(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IService/GetAlbums", ReplyAction = "http://tempuri.org/IService/GetAlbumsResponse")]
        System.IAsyncResult BeginGetAlbums(System.AsyncCallback callback, object asyncState);

        System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> EndGetAlbums(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/IService/UploadPhoto", ReplyAction = "http://tempuri.org/IService/UploadPhotoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MaFamilleService.CustomException), Action = "http://tempuri.org/IService/UploadPhotoCustomExceptionFault", Name = "CustomException", Namespace = "http://schemas.datacontract.org/2004/07/WcfService1.Model")]
        System.IAsyncResult BeginUploadPhoto(MaFamilleService.AlbumModel picture, System.AsyncCallback callback, object asyncState);

        void EndUploadPhoto(System.IAsyncResult result);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : MaFamilleService.IService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public string Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public MaFamilleService.CompositeType Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((MaFamilleService.CompositeType)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPhotosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetPhotosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel>)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTsunamiPhotosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetTsunamiPhotosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel> Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel>)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPhotoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetPhotoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public byte[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAlbumsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetAlbumsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel>)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<MaFamilleService.IService>, MaFamilleService.IService
    {

        private BeginOperationDelegate onBeginGetDataDelegate;

        private EndOperationDelegate onEndGetDataDelegate;

        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;

        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;

        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;

        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;

        private BeginOperationDelegate onBeginGetPhotosDelegate;

        private EndOperationDelegate onEndGetPhotosDelegate;

        private System.Threading.SendOrPostCallback onGetPhotosCompletedDelegate;

        private BeginOperationDelegate onBeginGetTsunamiPhotosDelegate;

        private EndOperationDelegate onEndGetTsunamiPhotosDelegate;

        private System.Threading.SendOrPostCallback onGetTsunamiPhotosCompletedDelegate;

        private BeginOperationDelegate onBeginGetPhotoDelegate;

        private EndOperationDelegate onEndGetPhotoDelegate;

        private System.Threading.SendOrPostCallback onGetPhotoCompletedDelegate;

        private BeginOperationDelegate onBeginGetAlbumsDelegate;

        private EndOperationDelegate onEndGetAlbumsDelegate;

        private System.Threading.SendOrPostCallback onGetAlbumsCompletedDelegate;

        private BeginOperationDelegate onBeginUploadPhotoDelegate;

        private EndOperationDelegate onEndUploadPhotoDelegate;

        private System.Threading.SendOrPostCallback onUploadPhotoCompletedDelegate;

        private BeginOperationDelegate onBeginOpenDelegate;

        private EndOperationDelegate onEndOpenDelegate;

        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;

        private BeginOperationDelegate onBeginCloseDelegate;

        private EndOperationDelegate onEndCloseDelegate;

        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;

        public ServiceClient()
        {
        }

        public ServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }

        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;

        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;

        public event System.EventHandler<GetPhotosCompletedEventArgs> GetPhotosCompleted;

        public event System.EventHandler<GetTsunamiPhotosCompletedEventArgs> GetTsunamiPhotosCompleted;

        public event System.EventHandler<GetPhotoCompletedEventArgs> GetPhotoCompleted;

        public event System.EventHandler<GetAlbumsCompletedEventArgs> GetAlbumsCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UploadPhotoCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MaFamilleService.IService.BeginGetData(int value, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string MaFamilleService.IService.EndGetData(System.IAsyncResult result)
        {
            return base.Channel.EndGetData(result);
        }

        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            int value = ((int)(inValues[0]));
            return ((MaFamilleService.IService)(this)).BeginGetData(value, callback, asyncState);
        }

        private object[] OnEndGetData(System.IAsyncResult result)
        {
            string retVal = ((MaFamilleService.IService)(this)).EndGetData(result);
            return new object[] {
                    retVal};
        }

        private void OnGetDataCompleted(object state)
        {
            if ((this.GetDataCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetDataAsync(int value)
        {
            this.GetDataAsync(value, null);
        }

        public void GetDataAsync(int value, object userState)
        {
            if ((this.onBeginGetDataDelegate == null))
            {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null))
            {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null))
            {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MaFamilleService.IService.BeginGetDataUsingDataContract(MaFamilleService.CompositeType composite, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaFamilleService.CompositeType MaFamilleService.IService.EndGetDataUsingDataContract(System.IAsyncResult result)
        {
            return base.Channel.EndGetDataUsingDataContract(result);
        }

        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MaFamilleService.CompositeType composite = ((MaFamilleService.CompositeType)(inValues[0]));
            return ((MaFamilleService.IService)(this)).BeginGetDataUsingDataContract(composite, callback, asyncState);
        }

        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result)
        {
            MaFamilleService.CompositeType retVal = ((MaFamilleService.IService)(this)).EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }

        private void OnGetDataUsingDataContractCompleted(object state)
        {
            if ((this.GetDataUsingDataContractCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetDataUsingDataContractAsync(MaFamilleService.CompositeType composite)
        {
            this.GetDataUsingDataContractAsync(composite, null);
        }

        public void GetDataUsingDataContractAsync(MaFamilleService.CompositeType composite, object userState)
        {
            if ((this.onBeginGetDataUsingDataContractDelegate == null))
            {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null))
            {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null))
            {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MaFamilleService.IService.BeginGetPhotos(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetPhotos(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> MaFamilleService.IService.EndGetPhotos(System.IAsyncResult result)
        {
            return base.Channel.EndGetPhotos(result);
        }

        private System.IAsyncResult OnBeginGetPhotos(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((MaFamilleService.IService)(this)).BeginGetPhotos(callback, asyncState);
        }

        private object[] OnEndGetPhotos(System.IAsyncResult result)
        {
            System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> retVal = ((MaFamilleService.IService)(this)).EndGetPhotos(result);
            return new object[] {
                    retVal};
        }

        private void OnGetPhotosCompleted(object state)
        {
            if ((this.GetPhotosCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPhotosCompleted(this, new GetPhotosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetPhotosAsync()
        {
            this.GetPhotosAsync(null);
        }

        public void GetPhotosAsync(object userState)
        {
            if ((this.onBeginGetPhotosDelegate == null))
            {
                this.onBeginGetPhotosDelegate = new BeginOperationDelegate(this.OnBeginGetPhotos);
            }
            if ((this.onEndGetPhotosDelegate == null))
            {
                this.onEndGetPhotosDelegate = new EndOperationDelegate(this.OnEndGetPhotos);
            }
            if ((this.onGetPhotosCompletedDelegate == null))
            {
                this.onGetPhotosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPhotosCompleted);
            }
            base.InvokeAsync(this.onBeginGetPhotosDelegate, null, this.onEndGetPhotosDelegate, this.onGetPhotosCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MaFamilleService.IService.BeginGetTsunamiPhotos(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetTsunamiPhotos(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel> MaFamilleService.IService.EndGetTsunamiPhotos(System.IAsyncResult result)
        {
            return base.Channel.EndGetTsunamiPhotos(result);
        }

        private System.IAsyncResult OnBeginGetTsunamiPhotos(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((MaFamilleService.IService)(this)).BeginGetTsunamiPhotos(callback, asyncState);
        }

        private object[] OnEndGetTsunamiPhotos(System.IAsyncResult result)
        {
            System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel> retVal = ((MaFamilleService.IService)(this)).EndGetTsunamiPhotos(result);
            return new object[] {
                    retVal};
        }

        private void OnGetTsunamiPhotosCompleted(object state)
        {
            if ((this.GetTsunamiPhotosCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTsunamiPhotosCompleted(this, new GetTsunamiPhotosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetTsunamiPhotosAsync()
        {
            this.GetTsunamiPhotosAsync(null);
        }

        public void GetTsunamiPhotosAsync(object userState)
        {
            if ((this.onBeginGetTsunamiPhotosDelegate == null))
            {
                this.onBeginGetTsunamiPhotosDelegate = new BeginOperationDelegate(this.OnBeginGetTsunamiPhotos);
            }
            if ((this.onEndGetTsunamiPhotosDelegate == null))
            {
                this.onEndGetTsunamiPhotosDelegate = new EndOperationDelegate(this.OnEndGetTsunamiPhotos);
            }
            if ((this.onGetTsunamiPhotosCompletedDelegate == null))
            {
                this.onGetTsunamiPhotosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTsunamiPhotosCompleted);
            }
            base.InvokeAsync(this.onBeginGetTsunamiPhotosDelegate, null, this.onEndGetTsunamiPhotosDelegate, this.onGetTsunamiPhotosCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MaFamilleService.IService.BeginGetPhoto(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetPhoto(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] MaFamilleService.IService.EndGetPhoto(System.IAsyncResult result)
        {
            return base.Channel.EndGetPhoto(result);
        }

        private System.IAsyncResult OnBeginGetPhoto(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((MaFamilleService.IService)(this)).BeginGetPhoto(callback, asyncState);
        }

        private object[] OnEndGetPhoto(System.IAsyncResult result)
        {
            byte[] retVal = ((MaFamilleService.IService)(this)).EndGetPhoto(result);
            return new object[] {
                    retVal};
        }

        private void OnGetPhotoCompleted(object state)
        {
            if ((this.GetPhotoCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPhotoCompleted(this, new GetPhotoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetPhotoAsync()
        {
            this.GetPhotoAsync(null);
        }

        public void GetPhotoAsync(object userState)
        {
            if ((this.onBeginGetPhotoDelegate == null))
            {
                this.onBeginGetPhotoDelegate = new BeginOperationDelegate(this.OnBeginGetPhoto);
            }
            if ((this.onEndGetPhotoDelegate == null))
            {
                this.onEndGetPhotoDelegate = new EndOperationDelegate(this.OnEndGetPhoto);
            }
            if ((this.onGetPhotoCompletedDelegate == null))
            {
                this.onGetPhotoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPhotoCompleted);
            }
            base.InvokeAsync(this.onBeginGetPhotoDelegate, null, this.onEndGetPhotoDelegate, this.onGetPhotoCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MaFamilleService.IService.BeginGetAlbums(System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetAlbums(callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> MaFamilleService.IService.EndGetAlbums(System.IAsyncResult result)
        {
            return base.Channel.EndGetAlbums(result);
        }

        private System.IAsyncResult OnBeginGetAlbums(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((MaFamilleService.IService)(this)).BeginGetAlbums(callback, asyncState);
        }

        private object[] OnEndGetAlbums(System.IAsyncResult result)
        {
            System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> retVal = ((MaFamilleService.IService)(this)).EndGetAlbums(result);
            return new object[] {
                    retVal};
        }

        private void OnGetAlbumsCompleted(object state)
        {
            if ((this.GetAlbumsCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAlbumsCompleted(this, new GetAlbumsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetAlbumsAsync()
        {
            this.GetAlbumsAsync(null);
        }

        public void GetAlbumsAsync(object userState)
        {
            if ((this.onBeginGetAlbumsDelegate == null))
            {
                this.onBeginGetAlbumsDelegate = new BeginOperationDelegate(this.OnBeginGetAlbums);
            }
            if ((this.onEndGetAlbumsDelegate == null))
            {
                this.onEndGetAlbumsDelegate = new EndOperationDelegate(this.OnEndGetAlbums);
            }
            if ((this.onGetAlbumsCompletedDelegate == null))
            {
                this.onGetAlbumsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAlbumsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAlbumsDelegate, null, this.onEndGetAlbumsDelegate, this.onGetAlbumsCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MaFamilleService.IService.BeginUploadPhoto(MaFamilleService.AlbumModel picture, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginUploadPhoto(picture, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MaFamilleService.IService.EndUploadPhoto(System.IAsyncResult result)
        {
            base.Channel.EndUploadPhoto(result);
        }

        private System.IAsyncResult OnBeginUploadPhoto(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MaFamilleService.AlbumModel picture = ((MaFamilleService.AlbumModel)(inValues[0]));
            return ((MaFamilleService.IService)(this)).BeginUploadPhoto(picture, callback, asyncState);
        }

        private object[] OnEndUploadPhoto(System.IAsyncResult result)
        {
            ((MaFamilleService.IService)(this)).EndUploadPhoto(result);
            return null;
        }

        private void OnUploadPhotoCompleted(object state)
        {
            if ((this.UploadPhotoCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadPhotoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void UploadPhotoAsync(MaFamilleService.AlbumModel picture)
        {
            this.UploadPhotoAsync(picture, null);
        }

        public void UploadPhotoAsync(MaFamilleService.AlbumModel picture, object userState)
        {
            if ((this.onBeginUploadPhotoDelegate == null))
            {
                this.onBeginUploadPhotoDelegate = new BeginOperationDelegate(this.OnBeginUploadPhoto);
            }
            if ((this.onEndUploadPhotoDelegate == null))
            {
                this.onEndUploadPhotoDelegate = new EndOperationDelegate(this.OnEndUploadPhoto);
            }
            if ((this.onUploadPhotoCompletedDelegate == null))
            {
                this.onUploadPhotoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadPhotoCompleted);
            }
            base.InvokeAsync(this.onBeginUploadPhotoDelegate, new object[] {
                        picture}, this.onEndUploadPhotoDelegate, this.onUploadPhotoCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }

        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }

        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void OpenAsync()
        {
            this.OpenAsync(null);
        }

        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }

        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }

        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CloseAsync()
        {
            this.CloseAsync(null);
        }

        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        protected override MaFamilleService.IService CreateChannel()
        {
            return new ServiceClientChannel(this);
        }

        private class ServiceClientChannel : ChannelBase<MaFamilleService.IService>, MaFamilleService.IService
        {

            public ServiceClientChannel(System.ServiceModel.ClientBase<MaFamilleService.IService> client) :
                base(client)
            {
            }

            public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = value;
                System.IAsyncResult _result = base.BeginInvoke("GetData", _args, callback, asyncState);
                return _result;
            }

            public string EndGetData(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetData", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetDataUsingDataContract(MaFamilleService.CompositeType composite, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = composite;
                System.IAsyncResult _result = base.BeginInvoke("GetDataUsingDataContract", _args, callback, asyncState);
                return _result;
            }

            public MaFamilleService.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MaFamilleService.CompositeType _result = ((MaFamilleService.CompositeType)(base.EndInvoke("GetDataUsingDataContract", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetPhotos(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPhotos", _args, callback, asyncState);
                return _result;
            }

            public System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> EndGetPhotos(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> _result = ((System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel>)(base.EndInvoke("GetPhotos", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetTsunamiPhotos(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTsunamiPhotos", _args, callback, asyncState);
                return _result;
            }

            public System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel> EndGetTsunamiPhotos(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel> _result = ((System.Collections.ObjectModel.ObservableCollection<MaFamilleService.TsunamiModel>)(base.EndInvoke("GetTsunamiPhotos", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetPhoto(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPhoto", _args, callback, asyncState);
                return _result;
            }

            public byte[] EndGetPhoto(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("GetPhoto", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetAlbums(System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAlbums", _args, callback, asyncState);
                return _result;
            }

            public System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> EndGetAlbums(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel> _result = ((System.Collections.ObjectModel.ObservableCollection<MaFamilleService.AlbumModel>)(base.EndInvoke("GetAlbums", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginUploadPhoto(MaFamilleService.AlbumModel picture, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = picture;
                System.IAsyncResult _result = base.BeginInvoke("UploadPhoto", _args, callback, asyncState);
                return _result;
            }

            public void EndUploadPhoto(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                base.EndInvoke("UploadPhoto", _args, result);
            }
        }
    }
}
