// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.Commands.DeleteCarCommand.#ctor(BoxedApiApplication1.Repositories.ICarRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.Commands.PatchCarCommand.#ctor(Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor,BoxedApiApplication1.Repositories.ICarRepository,Boxed.Mapping.IMapper{BoxedApiApplication1.Models.Car,BoxedApiApplication1.ViewModels.Car},Boxed.Mapping.IMapper{BoxedApiApplication1.Models.Car,BoxedApiApplication1.ViewModels.SaveCar},Boxed.Mapping.IMapper{BoxedApiApplication1.ViewModels.SaveCar,BoxedApiApplication1.Models.Car},FluentValidation.IValidator{BoxedApiApplication1.ViewModels.SaveCar})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.Commands.PostCarCommand.#ctor(Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor,BoxedApiApplication1.Repositories.ICarRepository,Boxed.Mapping.IMapper{BoxedApiApplication1.Models.Car,BoxedApiApplication1.ViewModels.Car},Boxed.Mapping.IMapper{BoxedApiApplication1.ViewModels.SaveCar,BoxedApiApplication1.Models.Car},FluentValidation.IValidator{BoxedApiApplication1.ViewModels.SaveCar})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.Commands.PutCarCommand.#ctor(Microsoft.AspNetCore.Mvc.Infrastructure.IActionContextAccessor,BoxedApiApplication1.Repositories.ICarRepository,Boxed.Mapping.IMapper{BoxedApiApplication1.Models.Car,BoxedApiApplication1.ViewModels.Car},Boxed.Mapping.IMapper{BoxedApiApplication1.ViewModels.SaveCar,BoxedApiApplication1.Models.Car},FluentValidation.IValidator{BoxedApiApplication1.ViewModels.SaveCar})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.ConfigureOptions.ConfigureJsonOptions.#ctor(Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.ConfigureOptions.ConfigureMvcOptions.#ctor(BoxedApiApplication1.Options.CacheProfileOptions)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.Mappers.CarToSaveCarMapper.#ctor(BoxedApiApplication1.Services.IClockService)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.Mappers.CarToCarMapper.#ctor(Microsoft.AspNetCore.Http.IHttpContextAccessor,Microsoft.AspNetCore.Routing.LinkGenerator)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.ConfigureOptions.ConfigureSwaggerUIOptions.#ctor(Microsoft.AspNetCore.Mvc.ApiExplorer.IApiVersionDescriptionProvider)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.ConfigureSwaggerGenOptions.#ctor(Microsoft.AspNetCore.Mvc.ApiExplorer.IApiVersionDescriptionProvider)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.ConfigureOptions.ConfigureStaticFileOptions.#ctor(BoxedApiApplication1.Options.CacheProfileOptions)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.ConfigureOptions.ConfigureResponseCompressionOptions.#ctor(BoxedApiApplication1.Options.CompressionOptions)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:BoxedApiApplication1.Startup.#ctor(Microsoft.Extensions.Configuration.IConfiguration,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
