using System;
using System.Data;
using System.Configuration;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
using System.Collections;
using System.Drawing;
using System.ComponentModel;

namespace CustomComponents
{
  public abstract class BaseMasterDetailControl2 : BaseMasterDetailControl
  {
    protected override Control CreateMaster()
    {
      BaseDataBoundControl master = this.CreateBaseDataBoundControlMaster();
      master.DataBound += new EventHandler(Master_DataBound);
      return master;
    }
    protected abstract void Master_DataBound(object sender, EventArgs e);
    protected abstract BaseDataBoundControl CreateBaseDataBoundControlMaster();
    protected override Control CreateDetail()
    {
      DetailsView detail = new DetailsView();
      detail.AllowPaging = false;
      detail.AutoGenerateDeleteButton = true;
      detail.AutoGenerateEditButton = true;
      detail.AutoGenerateInsertButton = true;
      detail.AutoGenerateRows = true;
      detail.ID = "DetailDetailsView";
      return detail;
    }
    protected override void RegisterDetailEventHandlers()
    {
      ((DetailsView)Detail).ItemDeleted +=
      new DetailsViewDeletedEventHandler(UpdateMaster);
      ((DetailsView)Detail).ItemInserted +=
      new DetailsViewInsertedEventHandler(UpdateMaster);
      ((DetailsView)Detail).ItemUpdated +=
      new DetailsViewUpdatedEventHandler(UpdateMaster);
    }
    public string MasterDataSourceID
    {
      get
      {
        return ((BaseDataBoundControl)Master).DataSourceID;
      }
      set
      {
        ((BaseDataBoundControl)Master).DataSourceID = value;
      }
    }
    public string DetailDataSourceID
    {
      get
      {
        return ((DetailsView)Detail).DataSourceID;
      }
      set
      {
        ((DetailsView)Detail).DataSourceID = value;
      }
    }
  }
}